# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Mak sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0650092306fd390e7c149a0d4e631987c475fef88cba0cebae5ba1f128fdcbe51cb0f5c8964affabba4c32ac0e2d4eb21b2c3d94c45fbf5a70eca261adf1c2

test:
  secret_key_base: 176fe4219dfc1e4f92db0bb7d5db33bf0cab3ab8cee279469b74446995092efd1ed2207b0c09b2f41b43aba38b5caae5efac30b2ea65ebb015fe2a718395291f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
